# Generated by Django 5.1.4 on 2025-01-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author', 'published_date', 'description']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
